mission_manager/default_speed: 1.28   # m/s
mission_manager/turn_radius: 1.0
mission_manager/hover_minimum_distance: 0.5
mission_manager/hover_maximum_distance: 2.0
mission_manager/hover_maximum_speed: 1.0 # m/s

mru_transform/sensors:
 - name: microstrain
   topics: { position: '/t1/p11_interface/fix', orientation: '/t1/p11_interface/imu', velocity: '/t1/p11_interface/twist'}

      
helm_manager/output_type: 'helm'
helm_manager/helm/max_speed: 2.75
helm_manager/helm/max_yaw_speed: 0.5

udp_bridge/remotes:
    operator:
        topics:
          navigator_costmap: {source: navigator/costmap/costmap}
          navigator_costmap_updates: {source: navigator/costmap/costmap_updates}

